//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCenter.ModulePage {
    
    
    public partial class ConfigDocumentSend {
        
        /// <summary>
        /// frmConfigDocumentSend control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm frmConfigDocumentSend;
        
        /// <summary>
        /// btnAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.ButtonEx btnAdd;
        
        /// <summary>
        /// ButtonEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.ButtonEx ButtonEx1;
        
        /// <summary>
        /// TransformEDIT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TransformEDIT;
        
        /// <summary>
        /// txtTaskCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx txtTaskCode;
        
        /// <summary>
        /// txtOrderNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx txtOrderNo;
        
        /// <summary>
        /// TextBoxEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx1;
        
        /// <summary>
        /// txtCOUNTRY_CODE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx txtCOUNTRY_CODE;
        
        /// <summary>
        /// TextBoxEx2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx2;
        
        /// <summary>
        /// TextBoxEx3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx3;
        
        /// <summary>
        /// TextBoxEx4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx4;
        
        /// <summary>
        /// TextBoxEx5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx5;
        
        /// <summary>
        /// TextBoxEx6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx6;
        
        /// <summary>
        /// TextBoxEx7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx7;
        
        /// <summary>
        /// TextBoxEx8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx8;
        
        /// <summary>
        /// TextBoxEx9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.TextBoxEx TextBoxEx9;
        
        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sourcesoft.ExControls.DataGridEx GridView1;
    }
}
